
// Automatically generated by flapigen
package com.example.jwst_demo.lib;

/*package*/ final class JNIReachabilityFence {
    private JNIReachabilityFence() {}
    /*package*/ static native void reachabilityFence1(Object ref1);
    /*package*/ static native void reachabilityFence2(Object ref1, Object ref2);
    /*package*/ static native void reachabilityFence3(Object ref1, Object ref2, Object ref3);
    /*package*/ static native void reachabilityFence4(Object ref1, Object ref2, Object ref3, Object ref4);
    /*package*/ static native void reachabilityFence5(Object ref1, Object ref2, Object ref3, Object ref4, Object ref5);
    /*package*/ static native void reachabilityFence6(Object ref1, Object ref2, Object ref3, Object ref4, Object ref5, Object ref6);
    /*package*/ static native void reachabilityFence7(Object ref1, Object ref2, Object ref3, Object ref4, Object ref5, Object ref6, Object ref7);
    /*package*/ static native void reachabilityFence8(Object ref1, Object ref2, Object ref3, Object ref4, Object ref5, Object ref6, Object ref7, Object ref8);}
