//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "update_binary")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub workspace: String,
    pub timestamp: DateTimeWithTimeZone,
    pub blob: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
