// Automatically generated by flapigen
package com.toeverything.jwst.lib;
import androidx.annotation.NonNull;

public interface BlockObserver {


    void onChange(@NonNull VecOfStrings block_ids);

}
