// Automatically generated by flapigen
package com.toeverything.jwst.lib;
import androidx.annotation.NonNull;

public interface OnWorkspaceTransaction {


    void onTrx(@NonNull WorkspaceTransaction trx);

}
