// Automatically generated by flapigen
package com.toeverything.jwst.lib;
import androidx.annotation.NonNull;

public final class WorkspaceTransaction {

    private WorkspaceTransaction() {
        mNativeObj = init();
    }
    private static native long init();

    public final boolean remove(@NonNull String block_id) {
        boolean ret = do_remove(mNativeObj, block_id);

        return ret;
    }
    private static native boolean do_remove(long self, @NonNull String block_id);

    public final @NonNull Block create(@NonNull String block_id, @NonNull String flavour) {
        long ret = do_create(mNativeObj, block_id, flavour);
        Block convRet = new Block(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_create(long self, @NonNull String block_id, @NonNull String flavour);

    public final void commit() {
        do_commit(mNativeObj);
    }
    private static native void do_commit(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ WorkspaceTransaction(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}