// Automatically generated by flapigen
package com.toeverything.jwst.lib;
import androidx.annotation.NonNull;

public final class Workspace {

    public Workspace(@NonNull String _id) {
        mNativeObj = init(_id);
    }
    private static native long init(@NonNull String _id);

    public final @NonNull String id() {
        String ret = do_id(mNativeObj);

        return ret;
    }
    private static native @NonNull String do_id(long self);

    public final long clientId() {
        long ret = do_clientId(mNativeObj);

        return ret;
    }
    private static native long do_clientId(long self);

    public final @NonNull Block create(@NonNull String block_id, @NonNull String flavour) {
        long ret = do_create(mNativeObj, block_id, flavour);
        Block convRet = new Block(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_create(long self, @NonNull String block_id, @NonNull String flavour);

    public final @NonNull java.util.Optional<Block> get(@NonNull String block_id) {
        long ret = do_get(mNativeObj, block_id);
        java.util.Optional<Block> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new Block(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        return convRet;
    }
    private static native long do_get(long self, @NonNull String block_id);

    public final @NonNull Block [] getBlocksByFlavour(@NonNull String flavour) {
        Block [] ret = do_getBlocksByFlavour(mNativeObj, flavour);

        return ret;
    }
    private static native @NonNull Block [] do_getBlocksByFlavour(long self, @NonNull String flavour);

    public final boolean exists(@NonNull String block_id) {
        boolean ret = do_exists(mNativeObj, block_id);

        return ret;
    }
    private static native boolean do_exists(long self, @NonNull String block_id);

    public final boolean remove(@NonNull String block_id) {
        boolean ret = do_remove(mNativeObj, block_id);

        return ret;
    }
    private static native boolean do_remove(long self, @NonNull String block_id);

    public final @NonNull String search(@NonNull String _query) {
        String ret = do_search(mNativeObj, _query);

        return ret;
    }
    private static native @NonNull String do_search(long self, @NonNull String _query);

    public final @NonNull java.lang.String [] getSearchIndex() {
        java.lang.String [] ret = do_getSearchIndex(mNativeObj);

        return ret;
    }
    private static native @NonNull java.lang.String [] do_getSearchIndex(long self);

    public final boolean setSearchIndex(@NonNull VecOfStrings _fields) {
        long a0 = _fields.mNativeObj;
        _fields.mNativeObj = 0;

        boolean ret = do_setSearchIndex(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(_fields);

        return ret;
    }
    private static native boolean do_setSearchIndex(long self, long _fields);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Workspace(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}