FROM messense/rust-musl-cross:armv7-musleabi AS builder
ENV CARGO_TERM_COLOR="always"
COPY . .
RUN --mount=type=cache,target=/root/.cargo/registry,rw,sharing=private \
    --mount=type=cache,target=/home/rust/src/target,rw,id=jwst_armv7 \
    cargo build --release --no-default-features --features jwst && \
    mv /home/rust/src/target/armv7-unknown-linux-musleabi/release/keck /tmp/jwst

FROM --platform=linux/amd64 ghcr.io/toeverything/affine:nightly-keck as static

FROM alpine:latest as jwst
WORKDIR /app
COPY --from=builder /tmp/jwst /usr/local/bin/jwst
COPY --from=builder /home/rust/src/apps/handbook/book ./book
COPY --from=static /app .
ENTRYPOINT /usr/local/bin/jwst