FROM ghcr.io/toeverything/affine-self-hosted:latest as frontend

FROM messense/rust-musl-cross:x86_64-musl AS builder-amd64
ENV CARGO_TERM_COLOR="always"
COPY . .
COPY --from=frontend /app/dist ./dist
RUN cargo build --release --no-default-features --features jwst --package keck && \
    mv /home/rust/src/target/x86_64-unknown-linux-musl/release/keck /tmp/jwst-amd64

FROM alpine:latest as relocate
WORKDIR /app
COPY --from=builder-amd64 /tmp/jwst-amd64 ./jwst

FROM alpine:latest as jwst
WORKDIR /app
COPY --from=relocate /app .
ENTRYPOINT /app/jwst