
ARG BASE_IMAGE=localhost:5000/toeverything/relocate:latest

FROM ${BASE_IMAGE} as builder

FROM --platform=linux/amd64 ghcr.io/toeverything/affine:nightly-keck as static

FROM alpine:latest as relocate
ARG TARGETPLATFORM
WORKDIR /app
COPY --from=builder /app/${TARGETPLATFORM}/jwst ./jwst
COPY --from=builder /app/${TARGETPLATFORM}/book ./book
COPY --from=static /app .

FROM alpine:latest as jwst
WORKDIR /app
COPY --from=relocate /app .
ENTRYPOINT /app/jwst