FROM messense/rust-musl-cross:aarch64-musl AS builder
ENV CARGO_TERM_COLOR="always"
COPY . .
RUN --mount=type=cache,target=/root/.cargo/registry,rw,sharing=private \
    --mount=type=cache,target=/home/rust/src/target,rw,id=jwst_aarch64 \
    cargo build --release --no-default-features && \
    mv /home/rust/src/target/aarch64-unknown-linux-musl/release/keck /tmp/jwst

FROM ghcr.io/toeverything/affine:nightly-keck as static

FROM alpine:latest as jwst
WORKDIR /app
COPY --from=builder /tmp/jwst /usr/local/bin/jwst
COPY --from=builder /home/rust/src/apps/handbook/book ./book
COPY --from=static /app .
ENTRYPOINT /usr/local/bin/jwst