FROM FROM ghcr.io/toeverything/affine-self-hosted:latest as frontend

FROM messense/rust-musl-cross:x86_64-musl AS builder-dependencies
ENV CARGO_TERM_COLOR="always"
COPY . .
RUN cargo vendor > .cargo/config

FROM messense/rust-musl-cross:x86_64-musl AS builder-amd64
ENV CARGO_TERM_COLOR="always" CARGO_BUILD_JOBS=2
COPY . .
COPY --from=builder-dependencies /home/rust/src/vendor /home/rust/src/vendor
COPY --from=builder-dependencies /home/rust/src/.cargo/config /home/rust/src/.cargo/config
COPY --from=frontend /app/dist ./dist
RUN --mount=type=cache,target=/home/rust/src/target,rw,id=jwst_amd64 \
    cargo build --release --no-default-features --features jwst --package keck && \
    mv /home/rust/src/target/x86_64-unknown-linux-musl/release/keck /tmp/jwst-amd64

FROM alpine:latest as relocate
WORKDIR /app
COPY --from=builder-amd64 /tmp/jwst-amd64 ./jwst

FROM alpine:latest as jwst
WORKDIR /app
COPY --from=relocate /app .
ENTRYPOINT /app/jwst