FROM messense/rust-musl-cross:x86_64-musl AS builder
ENV CARGO_TERM_COLOR="always"
RUN rustup update nightly && \
    rustup target add --toolchain nightly x86_64-unknown-linux-musl && \
    rustup default nightly
COPY . .
RUN cargo build --release

FROM ghcr.io/toeverything/affine:nightly-keck as static

FROM alpine:latest as affine
WORKDIR /app
COPY --from=builder \
    /home/rust/src/target/x86_64-unknown-linux-musl/release/keck \
    /usr/local/bin/affine
COPY --from=builder /home/rust/src/apps/handbook/book ./book
COPY --from=static /app .
ENTRYPOINT /usr/local/bin/affine