FROM messense/rust-musl-cross:x86_64-musl AS builder-dependencies
ENV CARGO_TERM_COLOR="always"
COPY . .
RUN cargo vendor > .cargo/config

FROM messense/rust-musl-cross:x86_64-musl AS builder-amd64
ENV CARGO_TERM_COLOR="always" CARGO_BUILD_JOBS=2
COPY . .
COPY --from=builder-dependencies /home/rust/src/vendor /home/rust/src/vendor
COPY --from=builder-dependencies /home/rust/src/.cargo/config /home/rust/src/.cargo/config
RUN --mount=type=cache,target=/home/rust/src/target,rw,id=cloud_amd64 \
    cargo build --release --no-default-features --package cloud && \
    mv /home/rust/src/target/x86_64-unknown-linux-musl/release/cloud /tmp/cloud-amd64

FROM ghcr.io/toeverything/affine:nightly-keck as relocate
WORKDIR /app
COPY --from=builder-amd64 /tmp/cloud-amd64 ./cloud

FROM alpine:latest as cloud
WORKDIR /app
COPY --from=relocate /app .
ENTRYPOINT /app/cloud