
ARG BASE_IMAGE=localhost:5000/toeverything/relocate:latest
ARG BASE_STATIC_IMAGE=ghcr.io/toeverything/affine-static:pre-alpha

FROM ${BASE_IMAGE} as builder

FROM --platform=linux/amd64 ${BASE_STATIC_IMAGE} as static

FROM alpine:latest as relocate
ARG TARGETPLATFORM
WORKDIR /app
COPY --from=builder /app/${TARGETPLATFORM}/affine ./affine
COPY --from=static /app .

FROM alpine:latest as affine
WORKDIR /app
COPY --from=relocate /app .
ENTRYPOINT /app/affine