
ARG BASE_IMAGE=localhost:5000/toeverything/relocate:latest

FROM ${BASE_IMAGE} as builder

FROM ghcr.io/toeverything/affine:nightly-keck as static

FROM --platform=linux/arm64/v8 alpine:latest as jwst-aarch64
WORKDIR /app
COPY --from=builder /tmp/jwst-aarch64 /usr/local/bin/jwst
COPY --from=builder /tmp/book-aarch64 ./book
COPY --from=static /app .
ENTRYPOINT /usr/local/bin/jwst

FROM --platform=linux/amd64 alpine:latest as jwst-amd64
WORKDIR /app
COPY --from=builder /tmp/jwst-amd64 /usr/local/bin/jwst
COPY --from=builder /tmp/book-amd64 ./book
COPY --from=static /app .
ENTRYPOINT /usr/local/bin/jwst

FROM --platform=linux/arm/v7 alpine:latest as jwst-armv7
WORKDIR /app
COPY --from=builder /tmp/jwst-armv7 /usr/local/bin/jwst
COPY --from=builder /tmp/book-armv7 ./book
COPY --from=static /app .
ENTRYPOINT /usr/local/bin/jwst