FROM messense/rust-musl-cross:x86_64-musl AS builder
ENV CARGO_TERM_COLOR="always"
RUN rustup update nightly && \
    rustup target add --toolchain nightly x86_64-unknown-linux-musl && \
    rustup default nightly
COPY . .
RUN --mount=type=cache,target=/root/.cargo/registry,rw,sharing=private \
    --mount=type=cache,target=/home/rust/src/target,rw,id=jwst_amd64 \
    cargo build --release --no-default-features && \
    mv /home/rust/src/target/x86_64-unknown-linux-musl/release/keck /tmp/jwst

FROM ghcr.io/toeverything/affine:nightly-keck as static

FROM alpine:latest as jwst
WORKDIR /app
COPY --from=builder /tmp/jwst /usr/local/bin/jwst
COPY --from=builder /home/rust/src/apps/handbook/book ./book
COPY --from=static /app .
ENTRYPOINT /usr/local/bin/jwst