FROM messense/rust-musl-cross:x86_64-musl AS builder
ENV CARGO_TERM_COLOR="always"
COPY . .
RUN --mount=type=cache,target=/root/.cargo/registry,rw,sharing=private \
    --mount=type=cache,target=/home/rust/src/target,rw,id=jwst_amd64 \
    cargo build --release --no-default-features --features affine && \
    mv /home/rust/src/target/x86_64-unknown-linux-musl/release/keck /tmp/affine

FROM ghcr.io/toeverything/affine:nightly-keck as static

FROM alpine:latest as affine
WORKDIR /app
COPY --from=builder /tmp/affine /usr/local/bin/affine
COPY --from=static /app .
ENTRYPOINT /usr/local/bin/affine