ARG BASE_STATIC_IMAGE=ghcr.io/toeverything/affine-pathfinder:canary-aae10d44e8893f9ee7fc45dfd72b7689b177ef88
FROM ${BASE_STATIC_IMAGE} as frontend

FROM messense/rust-musl-cross:x86_64-musl AS builder-amd64
ENV CARGO_TERM_COLOR="always"
COPY . .
COPY --from=frontend /app/dist ./dist
RUN cargo build --release --no-default-features --features affine --package affine-cloud && \
    mv /home/rust/src/target/x86_64-unknown-linux-musl/release/affine-cloud /tmp/cloud-amd64

FROM alpine:latest as relocate
WORKDIR /app
COPY --from=builder-amd64 /tmp/cloud-amd64 ./cloud

FROM alpine:latest as cloud
EXPOSE 3000
WORKDIR /app
COPY --from=relocate /app .
ENTRYPOINT /app/cloud