// Automatically generated by flapigen
package com.toeverything.jwst.lib;
import androidx.annotation.NonNull;

public final class Block {

    public Block(@NonNull Workspace workspace, @NonNull String block_id, @NonNull String flavor, long operator) {
        long a0 = workspace.mNativeObj;
        mNativeObj = init(a0, block_id, flavor, operator);
        JNIReachabilityFence.reachabilityFence1(workspace);
    }
    private static native long init(long workspace, @NonNull String block_id, @NonNull String flavor, long operator);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Block(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}