use axum::{
    extract::{Path, Query},
    response::Response,
};
use jwst_core::HistoryOptions;
use utoipa::IntoParams;

use super::*;

/// Block History Options
#[derive(Deserialize, IntoParams)]
pub struct BlockHistoryQuery {
    /// client id, is give 0 or empty then return all clients histories
    client: Option<u64>,
    /// skip count, available when client is set
    skip: Option<usize>,
    /// limit count, available when client is set
    limit: Option<usize>,
}

/// Get the history generated by a specific `Client ID` of the `Workspace`
///
/// If client id set to 0, return all history of the `Workspace`.
#[utoipa::path(
    get,
    tag = "Workspace",
    context_path = "/api/block",
    path = "/{workspace}/history",
    params(
        ("workspace", description = "workspace id"),
        BlockHistoryQuery,
    ),
    responses(
        (status = 200, description = "Get workspace history", body = [History]),
        (status = 400, description = "Client id invalid"),
        (status = 500, description = "Failed to get workspace history")
    )
)]
pub async fn history_workspace(
    Extension(context): Extension<Arc<Context>>,
    Path(ws_id): Path<String>,
    query: Query<BlockHistoryQuery>,
) -> Response {
    if let Ok(workspace) = context.get_workspace(&ws_id).await {
        Json(workspace.history(HistoryOptions {
            client: query.client,
            skip: query.skip,
            limit: query.limit,
        }))
        .into_response()
    } else {
        (StatusCode::NOT_FOUND, format!("Workspace({ws_id:?}) not found")).into_response()
    }
}
