/* auto-generated by NAPI-RS */
/* eslint-disable */

module a {
  export class Storage {
    static connect(database: string): Promise<Storage>;
    getOrCreateWorkspace(workspaceId: string): Promise<Workspace>;
  }

  export class Workspace {
    isEmpty(): boolean;
    id(): string;
    clientId(): bigint;
  }

  export function sum(a: number, b: number): number;
}

export default a;
