// File automatically generated by swift-bridge.
typedef struct Workspace Workspace;
void __swift_bridge__$Workspace$_free(void* self);

void* __swift_bridge__$Vec_Workspace$new(void);
void __swift_bridge__$Vec_Workspace$drop(void* vec_ptr);
void __swift_bridge__$Vec_Workspace$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Workspace$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Workspace$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Workspace$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Workspace$len(void* vec_ptr);
void* __swift_bridge__$Vec_Workspace$as_ptr(void* vec_ptr);

typedef struct Block Block;
void __swift_bridge__$Block$_free(void* self);

void* __swift_bridge__$Vec_Block$new(void);
void __swift_bridge__$Vec_Block$drop(void* vec_ptr);
void __swift_bridge__$Vec_Block$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_Block$pop(void* vec_ptr);
void* __swift_bridge__$Vec_Block$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_Block$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_Block$len(void* vec_ptr);
void* __swift_bridge__$Vec_Block$as_ptr(void* vec_ptr);

void* __swift_bridge__$Workspace$new(void* id);
void* __swift_bridge__$Workspace$get(void* self, void* block_id);
void* __swift_bridge__$Workspace$create(void* self, void* block_id, void* flavor);
void* __swift_bridge__$Block$to_string(void* self);


