//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.7

pub use super::{
    google_users::Entity as GoogleUsers, permissions::Entity as Permissions, users::Entity as Users,
    workspaces::Entity as Workspaces,
};
