//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::google_users::Entity as GoogleUsers;
pub use super::permissions::Entity as Permissions;
pub use super::users::Entity as Users;
pub use super::workspaces::Entity as Workspaces;
