//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub uuid: String,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub avatar_url: Option<String>,
    pub token_nonce: Option<i16>,
    pub password: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::google_users::Entity")]
    GoogleUsers,
    #[sea_orm(has_many = "super::permissions::Entity")]
    Permissions,
}

impl Related<super::google_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GoogleUsers.def()
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Permissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
