//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bucket_blobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub workspace: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub hash: String,
    pub length: i64,
    pub timestamp: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub params: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
