//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::{
    blobs::Entity as Blobs, bucket_blobs::Entity as BucketBlobs, diff_log::Entity as DiffLog, docs::Entity as Docs,
    optimized_blobs::Entity as OptimizedBlobs,
};
