//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::blobs::Entity as Blobs;
pub use super::docs::Entity as Docs;
pub use super::optimized_blobs::Entity as OptimizedBlobs;
pub use super::s3_blobs::Entity as S3Blobs;
