//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blobs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub workspace: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub hash: String,
    pub blob: Vec<u8>,
    pub length: i32,
    pub timestamp: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
