name: Memory Leak Detect

on:
    workflow_dispatch:
    push:
        branches: [master]
    pull_request:
        branches: [master]

# Cancels all previous workflow runs for pull requests that have not completed.
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # The concurrency group contains the workflow name and the branch name for
    # pull requests or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    miri:
        name: miri code check
        runs-on: ubuntu-latest
        continue-on-error: true
        env:
            RUST_BACKTRACE: full
            CARGO_TERM_COLOR: always
            MIRIFLAGS: -Zmiri-backtrace=full -Zmiri-tree-borrows
        steps:
            - uses: actions/checkout@v3

            - name: Setup Rust
              uses: ./.github/actions/setup-rust
              with:
                  toolchain: nightly-2023-08-19
                  components: miri
            - name: Install latest nextest release
              uses: taiki-e/install-action@nextest

            - name: Miri Code Check
              run: |
                  cargo +nightly-2023-08-19 miri nextest run -p jwst-codec -j2
