name: Address Sanitizer

on:
    workflow_dispatch:
    push:
        branches: [master]
    pull_request:
        branches: [master]

# Cancels all previous workflow runs for pull requests that have not completed.
# See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
    # The concurrency group contains the workflow name and the branch name for
    # pull requests or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    memory_check:
        name: memory check
        runs-on: ubuntu-latest
        continue-on-error: true
        env:
            RUSTFLAGS: -D warnings -Zsanitizer=address
            ASAN_OPTIONS: detect_leaks=1
            CARGO_TERM_COLOR: always
        steps:
            - uses: actions/checkout@v3

            - name: Setup Rust
              uses: ./.github/actions/setup-rust
              with:
                  toolchain: nightly-2023-08-19

            - name: Memory Check
              run: |
                  rustup component add rust-src --toolchain nightly-2023-08-19
                  cargo +nightly-2023-08-19 test -Zbuild-std --target x86_64-unknown-linux-gnu -p jwst-codec --lib
