name: Android Publish Package
on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@v1.1.0
            - uses: nttld/setup-ndk@v1
              id: setup-ndk
              with:
                  ndk-version: r25b
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: armv7-linux-androideabi
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: aarch64-linux-android
            - run: cargo install cargo-ndk
            - name: Publish package
              uses: gradle/gradle-build-action@v2.7.0
              with:
                  arguments: :jwst:publishReleasePublicationToGitHubPackagesRepository
                  build-root-directory: apps/android
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
